from LinkedList import *

print("Stack like:")
stack = LinkedList()
print("Push")
stack.push(4710)
stack.push(4711)
stack.push(4712)
stack.push("Martin")
stack.push(4714)
stack.push([1,2,3,4])
stack.push("Fridolin")
stack.push(object)
try:
  print(stack.search("Martin").data)
  print(stack.search("Daniel").data)
except AttributeError:
  print("Element not found in list")
stack.traversal()
stack.remove("Fridolin")
stack.remove("Hansdampf")

stack.traversal()
print("Pop")
print(stack.pop())
print(stack.pop())
print(stack.pop())
print(stack.pop())
print(stack.pop())
print(stack.pop())
print(stack.pop())
print()
print("FiFo like")
fifo = LinkedList()
print("Push")
fifo.push(4710)
fifo.push(4711)
fifo.push(4712)
fifo.push("Martin")
fifo.push(4714)
fifo.push([1,2,3,4])
fifo.push("Fridolin")
fifo.push(object)
print("FiFo traversal after Push:")
fifo.traversal()
print("Pop")
print(fifo.poll())
print(fifo.poll())
print(fifo.poll())
print(fifo.poll())
print(fifo.poll())
print(fifo.poll())
print(fifo.poll())
print(fifo.poll())
#print(fifo.poll())
